config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :agents
  root 'index#index'

  resources :ticket_threads
  resources :messages
  resources :message_queues
  resources :groups
  resources :organizations
  resources :tickets

end

app/models/ticket_thread.rb
class TicketThread < ActiveRecord::Base
  belongs_to :ticket
  has_many :messages
end

app/controllers/ticket_threads_controller.rb
class TicketThreadsController < ApplicationController
  before_action :set_ticket_thread, only: [:show, :edit, :update, :destroy]

  # GET /ticket_threads
  # GET /ticket_threads.json
  def index
    @ticket_threads = TicketThread.all
  end

  # GET /ticket_threads/1
  # GET /ticket_threads/1.json
  def show
  end

  # GET /ticket_threads/new
  def new
    @ticket_thread = TicketThread.new
  end

  # GET /ticket_threads/1/edit
  def edit
  end

  # POST /ticket_threads
  # POST /ticket_threads.json
  def create
    @ticket_thread = TicketThread.new(ticket_thread_params)

    respond_to do |format|
      if @ticket_thread.save
        format.html { redirect_to @ticket_thread, notice: 'Ticket thread was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_thread }
      else
        format.html { render :new }
        format.json { render json: @ticket_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_threads/1
  # PATCH/PUT /ticket_threads/1.json
  def update
    respond_to do |format|
      if @ticket_thread.update(ticket_thread_params)
        format.html { redirect_to @ticket_thread, notice: 'Ticket thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_thread }
      else
        format.html { render :edit }
        format.json { render json: @ticket_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_threads/1
  # DELETE /ticket_threads/1.json
  def destroy
    @ticket_thread.destroy
    respond_to do |format|
      format.html { redirect_to ticket_threads_url, notice: 'Ticket thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_thread
      @ticket_thread = TicketThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_thread_params
      params.require(:ticket_thread).permit(:name)
    end
end

app/helpers/ticket_threads_helper.rb
module TicketThreadsHelper
end

app/views/ticket_threads/_form.html.erb
<%= form_for(@ticket_thread) do |f| %>
  <% if @ticket_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_thread.errors.count, "error") %> prohibited this ticket_thread from being saved:</h2>

      <ul>
      <% @ticket_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_threads/edit.html.erb
<h1>Editing Ticket Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_thread %> |
<%= link_to 'Back', ticket_threads_path %>

app/views/ticket_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ticket Threads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_threads.each do |ticket_thread| %>
      <tr>
        <td><%= ticket_thread.name %></td>
        <td><%= link_to 'Show', ticket_thread %></td>
        <td><%= link_to 'Edit', edit_ticket_thread_path(ticket_thread) %></td>
        <td><%= link_to 'Destroy', ticket_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket thread', new_ticket_thread_path %>

app/views/ticket_threads/new.html.erb
<h1>New Ticket Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_threads_path %>

app/views/ticket_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket_thread.name %>
</p>

<%= link_to 'Edit', edit_ticket_thread_path(@ticket_thread) %> |
<%= link_to 'Back', ticket_threads_path %>